# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240417-172221-vintage-venison

language: vi

pipeline:
  - name: pipelines.Preprocesser.Preprocesser
  # - name: pipelines.VnCoreNLP.VnCoreNLPTokenizer
  - name: pipelines.Spacy.SpacyTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  # - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
  - name: LanguageModelFeaturizer # output: dense_feature
    model_name: bert
    model_weights: rasa/LaBSE
    cache_dir: null # change in the future to a path in server-side
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  # - name: pipelines.PrettyPrint.PrettyPrint
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies: null
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
